#Draw 3-color rectangles
import turtle

turtle.reset()
turtle.penup()
turtle.setpos(-100,50)
turtle.color ("red")
turtle.pendown()
turtle.begin_fill()
turtle.forward (200)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(50)
turtle.end_fill()

turtle.color ("green")
turtle.begin_fill()
turtle.forward (50)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(50)
turtle.end_fill()

turtle.color ("blue")
turtle.begin_fill()
turtle.forward (50)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(50)
turtle.end_fill()

